name: Deploy

on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [main, develop, release]
    types:
      - completed

jobs:
  deploy_storybook:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - run: echo "Deploy Storybook..."

  deploy_npm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - run: echo "Deploy to NPM..."
