name: Deploy

on:
  workflow_run:
    workflows: ["Build and test"]
    branches: [main, develop, release]
    types:
      - completed

env:
  node_version: 18

defaults:
  runs-on: ubuntu-latest

jobs:
  deploy_storybook:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.node_version }}
      - name: Debug (deploy_storybook)
        run: echo "Deploy Storybook..."

  deploy_npm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: test_build.yml
          name: build

      - name: Semantic release
        run: npx semantic-release
